-- LAWgico GTT — tabelas adicionais (Parcelamentos + Empregados)
create table public.gtt_parcelamentos (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.gtt_clientes(id) on delete cascade,
  empresa text not null,
  tipo_parcelamento text,
  numero_parcelamento text,
  total_parcelas integer,
  data_inicio date,
  data_fim date,
  competencia_ultimo_pagamento date,
  parcelas_pagas integer,
  parcelas_pendentes integer,
  parcelas_vencidas integer,
  status_geral text
);
alter table public.gtt_parcelamentos enable row level security;
create policy "authenticated full access" on public.gtt_parcelamentos for all to authenticated using (true) with check (true);

create table public.gtt_empregados (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.gtt_clientes(id) on delete cascade,
  fornecedor text,
  nome text not null,
  cargo text,
  departamento text,
  status text default 'Ativo',
  criado_em timestamptz default now()
);
alter table public.gtt_empregados enable row level security;
create policy "authenticated full access" on public.gtt_empregados for all to authenticated using (true) with check (true);

-- ── Acesso por cliente ──────────────────────────────────────────────
-- Cada usuário (P&C ou o cliente, ex: BAT/Whirlpool) só enxerga os
-- cliente_id vinculados a ele. Usuários da P&C ficam vinculados a TODOS
-- os clientes (is_staff = true); usuário de cliente só ao(s) seu(s).
create table public.gtt_usuarios_acesso (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  cliente_id bigint references public.gtt_clientes(id) on delete cascade,
  is_staff boolean not null default false,  -- true = P&C, enxerga todos os clientes
  unique (user_id, cliente_id)
);
alter table public.gtt_usuarios_acesso enable row level security;
create policy "usuário vê seu próprio acesso" on public.gtt_usuarios_acesso for select to authenticated using (user_id = auth.uid());

-- P&C (você) como staff, enxerga todos os clientes:
insert into public.gtt_usuarios_acesso (user_id, cliente_id, is_staff)
select id, null, true from auth.users where email = 'anacarolina.martini@peixotoecury.com.br';

-- Substitui as policies genéricas "authenticated full access" por
-- policies que checam o vínculo cliente_id em gtt_usuarios_acesso.
drop policy if exists "authenticated full access" on public.gtt_clientes;
drop policy if exists "authenticated full access" on public.gtt_fornecedores;
drop policy if exists "authenticated full access" on public.gtt_compliance_mensal;
drop policy if exists "authenticated full access" on public.gtt_irregularidades;
drop policy if exists "authenticated full access" on public.gtt_processos;
drop policy if exists "authenticated full access" on public.gtt_terceiros_localidade;
drop policy if exists "authenticated full access" on public.gtt_documentos;

create or replace function public.gtt_pode_acessar(p_cliente_id bigint)
returns boolean language sql stable security definer as $$
  select exists (
    select 1 from public.gtt_usuarios_acesso
    where user_id = auth.uid() and (is_staff = true or cliente_id = p_cliente_id)
  );
$$;

create policy "acesso por cliente" on public.gtt_clientes for all to authenticated using (public.gtt_pode_acessar(id)) with check (public.gtt_pode_acessar(id));
create policy "acesso por cliente" on public.gtt_fornecedores for all to authenticated using (public.gtt_pode_acessar(cliente_id)) with check (public.gtt_pode_acessar(cliente_id));
create policy "acesso por cliente" on public.gtt_compliance_mensal for all to authenticated using (public.gtt_pode_acessar(cliente_id)) with check (public.gtt_pode_acessar(cliente_id));
create policy "acesso por cliente" on public.gtt_irregularidades for all to authenticated using (public.gtt_pode_acessar(cliente_id)) with check (public.gtt_pode_acessar(cliente_id));
create policy "acesso por cliente" on public.gtt_processos for all to authenticated using (public.gtt_pode_acessar(cliente_id)) with check (public.gtt_pode_acessar(cliente_id));
create policy "acesso por cliente" on public.gtt_terceiros_localidade for all to authenticated using (public.gtt_pode_acessar(cliente_id)) with check (public.gtt_pode_acessar(cliente_id));
create policy "acesso por cliente" on public.gtt_documentos for all to authenticated using (public.gtt_pode_acessar(cliente_id)) with check (public.gtt_pode_acessar(cliente_id));
create policy "acesso por cliente" on public.gtt_parcelamentos for all to authenticated using (public.gtt_pode_acessar(cliente_id)) with check (public.gtt_pode_acessar(cliente_id));
create policy "acesso por cliente" on public.gtt_empregados for all to authenticated using (public.gtt_pode_acessar(cliente_id)) with check (public.gtt_pode_acessar(cliente_id));

NOTIFY pgrst, 'reload schema';
