-- LAWgico GTT — Gestão de Terceiros e Temporários
-- Rodar no SQL Editor do mesmo projeto Supabase (rpibvjcnrseuugpkfmdj), igual aos outros LAWgico.

create table public.gtt_clientes (
  id bigint generated by default as identity primary key,
  nome text not null,
  slug text not null unique,
  criado_em timestamptz default now()
);

create table public.gtt_fornecedores (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.gtt_clientes(id) on delete cascade,
  empresa text not null,
  cnpj text,
  status text,                    -- Ativo / Inativa
  cadastro_gtt text,
  parcelamento_fgts text,
  usuarios_cadastrados text,
  fase_anterior text,
  fase_atual text,
  inicio_documentacao date,
  contrato_social text,
  inscricao_junta text,
  vencimento_contrato date,
  status_contrato text,           -- Vigente / Vencido / Vencimento Próximo / Aguardando documento
  descricao_contrato text,
  prorrogavel text,
  localidades text,
  observacoes text,
  atualizado_em timestamptz default now(),
  unique (cliente_id, cnpj)
);

create table public.gtt_compliance_mensal (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.gtt_clientes(id) on delete cascade,
  empresa text not null,
  mes_referencia date not null,
  compliance numeric,              -- fração 0-1
  unique (cliente_id, empresa, mes_referencia)
);

create table public.gtt_irregularidades (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.gtt_clientes(id) on delete cascade,
  empresa text not null,
  mes_referencia date not null,
  cartoes_britanico numeric,
  horas_extras_2h numeric,
  intervalo_intrajornada numeric,
  intervalo_interjornada numeric,
  dsr numeric,
  qtd_terceiros_ativos numeric,
  qtd_terceiros_analisados numeric,
  pct_docs_empregado_analisado numeric,
  total_rescisoes numeric,
  total_docs_rescisoes numeric,
  irregularidades_rescisoes numeric,
  irregularidades_trct numeric,
  irregularidades_grrf numeric,
  irregularidades_contrato_trabalho numeric,
  irregularidades_ficha_registro numeric,
  irregularidades_ficha_epi numeric,
  irregularidades_recibo_ferias numeric,
  irregularidades_fgts numeric,
  irregularidades_inss numeric,
  unique (cliente_id, empresa, mes_referencia)
);

create table public.gtt_processos (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.gtt_clientes(id) on delete cascade,
  numero_processo text not null,
  assunto text,
  cnpjs text,
  situacao text,
  data_distribuicao date,
  ano_distribuicao integer,
  comarca text,
  vara text,
  uf text,
  tribunal text,
  fase text,
  instancia text,
  classe text,
  tipo_recurso text,
  valor_causa numeric,
  valor_deposito numeric,
  valor_condenacao numeric,
  valor_liquidacao numeric,
  valor_custas numeric,
  empresa_reclamada text,
  desfecho text,
  atualizado_em timestamptz default now(),
  unique (cliente_id, numero_processo)
);

create table public.gtt_terceiros_localidade (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.gtt_clientes(id) on delete cascade,
  empresa text not null,
  filial text,
  cidade text,
  uf text,
  pais text,
  mes_referencia date not null,
  qtd_funcionarios numeric,
  unique (cliente_id, empresa, filial, mes_referencia)
);

create table public.gtt_documentos (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.gtt_clientes(id) on delete cascade,
  uf text,
  empresa text not null,
  documento text not null,
  mes_referencia date not null,
  status text,   -- regular / irregular / parcial / dispensado
  unique (cliente_id, empresa, documento, mes_referencia)
);

alter table public.gtt_clientes enable row level security;
alter table public.gtt_fornecedores enable row level security;
alter table public.gtt_compliance_mensal enable row level security;
alter table public.gtt_irregularidades enable row level security;
alter table public.gtt_processos enable row level security;
alter table public.gtt_terceiros_localidade enable row level security;
alter table public.gtt_documentos enable row level security;

-- Só usuário logado (Supabase Auth) acessa — diferente dos outros LAWgico
-- (que usam senha compartilhada), esse tem login individual de verdade.
create policy "authenticated full access" on public.gtt_clientes for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.gtt_fornecedores for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.gtt_compliance_mensal for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.gtt_irregularidades for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.gtt_processos for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.gtt_terceiros_localidade for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.gtt_documentos for all to authenticated using (true) with check (true);

insert into public.gtt_clientes (nome, slug) values ('BAT', 'bat');

NOTIFY pgrst, 'reload schema';
