-- LAWgico GTT — parcelas individuais (das 6 abas Parcelamento Sysconnect/
-- Manserv/Prado Chaves/Alert/Straatmann & Wende/Scapini) + campo que
-- faltava em Irregularidades (coluna G sem nome no cabeçalho da origem).

create table public.gtt_parcelas_detalhe (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.gtt_clientes(id) on delete cascade,
  empresa text not null,
  titulo_debito text,
  numero_prestacao text,
  competencia_vencimento date,
  comprovante text,
  fonte_planilha text
);
alter table public.gtt_parcelas_detalhe enable row level security;
create policy "acesso por cliente" on public.gtt_parcelas_detalhe for all to authenticated using (public.gtt_pode_acessar(cliente_id)) with check (public.gtt_pode_acessar(cliente_id));

alter table public.gtt_irregularidades add column if not exists total_geral numeric;

alter table public.gtt_clientes add column if not exists cnpj text;
alter table public.gtt_clientes add column if not exists segmento text;
alter table public.gtt_clientes add column if not exists status text default 'Ativo';

NOTIFY pgrst, 'reload schema';
